#!/usr/bin/perl -w

use EEC;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "EEC",
   ReceiveHandler => \&Receive);
$UNIVERSAL::eec = EEC->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::eec->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::eec->Execute();
