#!/usr/bin/perl -w

use Com::elle::bLeaf::EvidenceGenerator;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "Evidence-Generator",
   ReceiveHandler => \&Receive);
$UNIVERSAL::evidencegenerator = Com::elle::bLeaf::EvidenceGenerator->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::evidencegenerator->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::evidencegenerator->Execute();


# #!/usr/bin/perl -w

# use Com::elle::bLeaf::EvidenceGenerator;

# my $evidencegenerator = Com::elle::bLeaf::EvidenceGenerator->new();
# $evidencegenerator->Execute(Items => \@ARGV);
